version: "3.9"

services:
  redis:
    container_name: "ts-redis"
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
#     networks:
#       ts-node-net:
#         ipv4_address: 172.28.1.4

# # networking for the Redis container
# networks:
#   ts-node-net:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.0.0/16
